version: 1.0.{build}

image: Visual Studio 2017

environment:
    matrix:
    - solution_name: MyThreadPool/MyThreadPool.sln

before_build:
  - cmd: nuget restore MyThreadPool/MyThreadPool.sln
    
build_script:
    - msbuild MyThreadPool/MyThreadPool.sln