image: Visual Studio 2017

before_build:
    - nuget restore "4 semestr/Test1/Test1.sln"
    
build:
    project: "4 semestr/Test1/Test1.sln"
    
test_script:
    - dotnet test "4 semestr/Test1/Test1.sln"