    
    version: 1.0.{build}

image: Visual Studio 2017
      
for:
-
  branches:
    only:
      - master
      
  
  environment:
      matrix:
        - solution_name: Lazy/Lazy.sln

  before_build:
    - cmd: nuget restore Lazy/Lazy.sln

  build_script:
    - msbuild Lazy/Lazy.sln

-
  branches:
    only:
      - simpleftp

  environment:
    matrix:
     - solution_name: SimpleFTPServer/SimpleFTPServer.sln    
     - solution_name: SimpleFTPClient/SimpleFTPClient.sln
  
  build_script:
    - msbuild SimpleFTPServer/SimpleFTPServer.sln    
    - msbuild SimpleFTPClient/SimpleFTPClient.sln